@Todo_HostAddress = http://localhost:5099

###

GET {{Todo_HostAddress}}/Todo/all
Accept: application/json

###

POST {{Todo_HostAddress}}/Todo
Authorization: Bearer 
Content-Type: application/json

{
  "Title": "Homework",
  "Description": "Easy"
}

###

POST {{Todo_HostAddress}}/register
Content-Type: application/json
Accept: application/json

{
  "email": "q@gmail.com",
  "password": ""
}

###

POST {{Todo_HostAddress}}/login
content-Type: application/json

{
  "email": "q@gmail.com",
  "password": ""
}